// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: jsonrpc.proto

package solanajsonrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	JsonRpc_Get_FullMethodName  = "/solanajsonrpc.JsonRpc/Get"
	JsonRpc_Post_FullMethodName = "/solanajsonrpc.JsonRpc/Post"
)

// JsonRpcClient is the client API for JsonRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JsonRpcClient interface {
	Get(ctx context.Context, in *Header, opts ...grpc.CallOption) (*Response, error)
	Post(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type jsonRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewJsonRpcClient(cc grpc.ClientConnInterface) JsonRpcClient {
	return &jsonRpcClient{cc}
}

func (c *jsonRpcClient) Get(ctx context.Context, in *Header, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, JsonRpc_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jsonRpcClient) Post(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, JsonRpc_Post_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JsonRpcServer is the server API for JsonRpc service.
// All implementations must embed UnimplementedJsonRpcServer
// for forward compatibility
type JsonRpcServer interface {
	Get(context.Context, *Header) (*Response, error)
	Post(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedJsonRpcServer()
}

// UnimplementedJsonRpcServer must be embedded to have forward compatible implementations.
type UnimplementedJsonRpcServer struct {
}

func (UnimplementedJsonRpcServer) Get(context.Context, *Header) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedJsonRpcServer) Post(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Post not implemented")
}
func (UnimplementedJsonRpcServer) mustEmbedUnimplementedJsonRpcServer() {}

// UnsafeJsonRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JsonRpcServer will
// result in compilation errors.
type UnsafeJsonRpcServer interface {
	mustEmbedUnimplementedJsonRpcServer()
}

func RegisterJsonRpcServer(s grpc.ServiceRegistrar, srv JsonRpcServer) {
	s.RegisterService(&JsonRpc_ServiceDesc, srv)
}

func _JsonRpc_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Header)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JsonRpcServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JsonRpc_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JsonRpcServer).Get(ctx, req.(*Header))
	}
	return interceptor(ctx, in, info, handler)
}

func _JsonRpc_Post_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JsonRpcServer).Post(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JsonRpc_Post_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JsonRpcServer).Post(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// JsonRpc_ServiceDesc is the grpc.ServiceDesc for JsonRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JsonRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "solanajsonrpc.JsonRpc",
	HandlerType: (*JsonRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _JsonRpc_Get_Handler,
		},
		{
			MethodName: "Post",
			Handler:    _JsonRpc_Post_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jsonrpc.proto",
}
