// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: catscope.proto

package catscope

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catscope_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_catscope_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_catscope_proto_rawDescGZIP(), []int{0}
}

type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListId []*AccountId `protobuf:"bytes,1,rep,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catscope_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catscope_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_catscope_proto_rawDescGZIP(), []int{1}
}

func (x *GetRequest) GetListId() []*AccountId {
	if x != nil {
		return x.ListId
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListAccount []*Account `protobuf:"bytes,1,rep,name=list_account,json=listAccount,proto3" json:"list_account,omitempty"`
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catscope_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catscope_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_catscope_proto_rawDescGZIP(), []int{2}
}

func (x *GetResponse) GetListAccount() []*Account {
	if x != nil {
		return x.ListAccount
	}
	return nil
}

type AccountId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Id:
	//
	//	*AccountId_NodeId
	//	*AccountId_Pubkey
	Id isAccountId_Id `protobuf_oneof:"id"`
}

func (x *AccountId) Reset() {
	*x = AccountId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catscope_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountId) ProtoMessage() {}

func (x *AccountId) ProtoReflect() protoreflect.Message {
	mi := &file_catscope_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountId.ProtoReflect.Descriptor instead.
func (*AccountId) Descriptor() ([]byte, []int) {
	return file_catscope_proto_rawDescGZIP(), []int{3}
}

func (m *AccountId) GetId() isAccountId_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (x *AccountId) GetNodeId() uint64 {
	if x, ok := x.GetId().(*AccountId_NodeId); ok {
		return x.NodeId
	}
	return 0
}

func (x *AccountId) GetPubkey() []byte {
	if x, ok := x.GetId().(*AccountId_Pubkey); ok {
		return x.Pubkey
	}
	return nil
}

type isAccountId_Id interface {
	isAccountId_Id()
}

type AccountId_NodeId struct {
	NodeId uint64 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3,oneof"`
}

type AccountId_Pubkey struct {
	Pubkey []byte `protobuf:"bytes,2,opt,name=pubkey,proto3,oneof"`
}

func (*AccountId_NodeId) isAccountId_Id() {}

func (*AccountId_Pubkey) isAccountId_Id() {}

type Account struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header         []byte  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data           []byte  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ListEdgeAdd    []*Edge `protobuf:"bytes,3,rep,name=list_edge_add,json=listEdgeAdd,proto3" json:"list_edge_add,omitempty"`
	ListEdgeDelete []*Edge `protobuf:"bytes,4,rep,name=list_edge_delete,json=listEdgeDelete,proto3" json:"list_edge_delete,omitempty"`
	ListEdgeKeep   []*Edge `protobuf:"bytes,5,rep,name=list_edge_keep,json=listEdgeKeep,proto3" json:"list_edge_keep,omitempty"`
}

func (x *Account) Reset() {
	*x = Account{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catscope_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_catscope_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_catscope_proto_rawDescGZIP(), []int{4}
}

func (x *Account) GetHeader() []byte {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Account) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Account) GetListEdgeAdd() []*Edge {
	if x != nil {
		return x.ListEdgeAdd
	}
	return nil
}

func (x *Account) GetListEdgeDelete() []*Edge {
	if x != nil {
		return x.ListEdgeDelete
	}
	return nil
}

func (x *Account) GetListEdgeKeep() []*Edge {
	if x != nil {
		return x.ListEdgeKeep
	}
	return nil
}

type SubscriptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Root         *AccountId `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	FilterWeight uint32     `protobuf:"varint,2,opt,name=filter_weight,json=filterWeight,proto3" json:"filter_weight,omitempty"`
	Depth        uint32     `protobuf:"varint,3,opt,name=depth,proto3" json:"depth,omitempty"`
	LastSlot     uint64     `protobuf:"varint,4,opt,name=last_slot,json=lastSlot,proto3" json:"last_slot,omitempty"`
}

func (x *SubscriptionRequest) Reset() {
	*x = SubscriptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catscope_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionRequest) ProtoMessage() {}

func (x *SubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catscope_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionRequest.ProtoReflect.Descriptor instead.
func (*SubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_catscope_proto_rawDescGZIP(), []int{5}
}

func (x *SubscriptionRequest) GetRoot() *AccountId {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *SubscriptionRequest) GetFilterWeight() uint32 {
	if x != nil {
		return x.FilterWeight
	}
	return 0
}

func (x *SubscriptionRequest) GetDepth() uint32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *SubscriptionRequest) GetLastSlot() uint64 {
	if x != nil {
		return x.LastSlot
	}
	return 0
}

type ChainUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Update:
	//
	//	*ChainUpdate_Slot
	//	*ChainUpdate_Blockhash
	Update isChainUpdate_Update `protobuf_oneof:"update"`
}

func (x *ChainUpdate) Reset() {
	*x = ChainUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catscope_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChainUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainUpdate) ProtoMessage() {}

func (x *ChainUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_catscope_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainUpdate.ProtoReflect.Descriptor instead.
func (*ChainUpdate) Descriptor() ([]byte, []int) {
	return file_catscope_proto_rawDescGZIP(), []int{6}
}

func (m *ChainUpdate) GetUpdate() isChainUpdate_Update {
	if m != nil {
		return m.Update
	}
	return nil
}

func (x *ChainUpdate) GetSlot() *Slot {
	if x, ok := x.GetUpdate().(*ChainUpdate_Slot); ok {
		return x.Slot
	}
	return nil
}

func (x *ChainUpdate) GetBlockhash() []byte {
	if x, ok := x.GetUpdate().(*ChainUpdate_Blockhash); ok {
		return x.Blockhash
	}
	return nil
}

type isChainUpdate_Update interface {
	isChainUpdate_Update()
}

type ChainUpdate_Slot struct {
	Slot *Slot `protobuf:"bytes,1,opt,name=slot,proto3,oneof"`
}

type ChainUpdate_Blockhash struct {
	Blockhash []byte `protobuf:"bytes,2,opt,name=blockhash,proto3,oneof"`
}

func (*ChainUpdate_Slot) isChainUpdate_Update() {}

func (*ChainUpdate_Blockhash) isChainUpdate_Update() {}

type Slot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slot   uint64 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Status uint32 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Slot) Reset() {
	*x = Slot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catscope_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Slot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slot) ProtoMessage() {}

func (x *Slot) ProtoReflect() protoreflect.Message {
	mi := &file_catscope_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slot.ProtoReflect.Descriptor instead.
func (*Slot) Descriptor() ([]byte, []int) {
	return file_catscope_proto_rawDescGZIP(), []int{7}
}

func (x *Slot) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *Slot) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type Edge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From   uint64 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To     uint64 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	Weight uint32 `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
}

func (x *Edge) Reset() {
	*x = Edge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catscope_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_catscope_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_catscope_proto_rawDescGZIP(), []int{8}
}

func (x *Edge) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Edge) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *Edge) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type SubscriptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slot        uint64     `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	ListAccount []*Account `protobuf:"bytes,2,rep,name=list_account,json=listAccount,proto3" json:"list_account,omitempty"`
}

func (x *SubscriptionResponse) Reset() {
	*x = SubscriptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catscope_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionResponse) ProtoMessage() {}

func (x *SubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catscope_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionResponse.ProtoReflect.Descriptor instead.
func (*SubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_catscope_proto_rawDescGZIP(), []int{9}
}

func (x *SubscriptionResponse) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *SubscriptionResponse) GetListAccount() []*Account {
	if x != nil {
		return x.ListAccount
	}
	return nil
}

type RentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size uint64 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *RentRequest) Reset() {
	*x = RentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catscope_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RentRequest) ProtoMessage() {}

func (x *RentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catscope_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RentRequest.ProtoReflect.Descriptor instead.
func (*RentRequest) Descriptor() ([]byte, []int) {
	return file_catscope_proto_rawDescGZIP(), []int{10}
}

func (x *RentRequest) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type RentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size uint64 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *RentResponse) Reset() {
	*x = RentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catscope_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RentResponse) ProtoMessage() {}

func (x *RentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catscope_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RentResponse.ProtoReflect.Descriptor instead.
func (*RentResponse) Descriptor() ([]byte, []int) {
	return file_catscope_proto_rawDescGZIP(), []int{11}
}

func (x *RentResponse) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_catscope_proto protoreflect.FileDescriptor

var file_catscope_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x61, 0x74, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0d, 0x63, 0x61, 0x74, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22,
	0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x3f, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x07, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x61, 0x74, 0x73, 0x63, 0x6f,
	0x70, 0x65, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49,
	0x64, 0x52, 0x06, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x22, 0x48, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0c, 0x6c, 0x69, 0x73, 0x74,
	0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x63, 0x61, 0x74, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x0b, 0x6c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x46, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x19, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x48, 0x00, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x06, 0x70,
	0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x70,
	0x75, 0x62, 0x6b, 0x65, 0x79, 0x42, 0x04, 0x0a, 0x02, 0x69, 0x64, 0x22, 0xe8, 0x01, 0x0a, 0x07,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x37, 0x0a, 0x0d, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x65, 0x64, 0x67, 0x65,
	0x5f, 0x61, 0x64, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x61, 0x74,
	0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x45, 0x64, 0x67, 0x65, 0x52,
	0x0b, 0x6c, 0x69, 0x73, 0x74, 0x45, 0x64, 0x67, 0x65, 0x41, 0x64, 0x64, 0x12, 0x3d, 0x0a, 0x10,
	0x6c, 0x69, 0x73, 0x74, 0x5f, 0x65, 0x64, 0x67, 0x65, 0x5f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x61, 0x74, 0x73, 0x63, 0x6f, 0x70,
	0x65, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x45, 0x64, 0x67, 0x65, 0x52, 0x0e, 0x6c, 0x69, 0x73,
	0x74, 0x45, 0x64, 0x67, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x39, 0x0a, 0x0e, 0x6c,
	0x69, 0x73, 0x74, 0x5f, 0x65, 0x64, 0x67, 0x65, 0x5f, 0x6b, 0x65, 0x65, 0x70, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x61, 0x74, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x2e, 0x45, 0x64, 0x67, 0x65, 0x52, 0x0c, 0x6c, 0x69, 0x73, 0x74, 0x45, 0x64,
	0x67, 0x65, 0x4b, 0x65, 0x65, 0x70, 0x22, 0x9b, 0x01, 0x0a, 0x13, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c,
	0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63,
	0x61, 0x74, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x12, 0x23, 0x0a, 0x0d,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x5f, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0c, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x57, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x70, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x64, 0x65, 0x70, 0x74, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f,
	0x73, 0x6c, 0x6f, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74,
	0x53, 0x6c, 0x6f, 0x74, 0x22, 0x62, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x29, 0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x63, 0x61, 0x74, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x48, 0x00, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x12, 0x1e,
	0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x48, 0x00, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x68, 0x61, 0x73, 0x68, 0x42, 0x08,
	0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x32, 0x0a, 0x04, 0x53, 0x6c, 0x6f, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04,
	0x73, 0x6c, 0x6f, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x42, 0x0a, 0x04,
	0x45, 0x64, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x22, 0x65, 0x0a, 0x14, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x12, 0x39, 0x0a, 0x0c,
	0x6c, 0x69, 0x73, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x61, 0x74, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x0b, 0x6c, 0x69, 0x73, 0x74,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x21, 0x0a, 0x0b, 0x52, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x22, 0x0a, 0x0c, 0x52, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x32, 0xa6,
	0x02, 0x0a, 0x05, 0x47, 0x72, 0x61, 0x70, 0x68, 0x12, 0x3c, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12,
	0x19, 0x2e, 0x63, 0x61, 0x74, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x63, 0x61, 0x74,
	0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x12, 0x22, 0x2e, 0x63, 0x61, 0x74, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x63, 0x61, 0x74, 0x73, 0x63, 0x6f,
	0x70, 0x65, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01,
	0x12, 0x3b, 0x0a, 0x05, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x14, 0x2e, 0x63, 0x61, 0x74, 0x73,
	0x63, 0x6f, 0x70, 0x65, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x1a, 0x2e, 0x63, 0x61, 0x74, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e,
	0x43, 0x68, 0x61, 0x69, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x30, 0x01, 0x12, 0x48, 0x0a,
	0x0d, 0x52, 0x65, 0x6e, 0x74, 0x45, 0x78, 0x65, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a,
	0x2e, 0x63, 0x61, 0x74, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x52,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x63, 0x61, 0x74,
	0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x61, 0x64, 0x2f, 0x73,
	0x6f, 0x6c, 0x70, 0x69, 0x70, 0x65, 0x2d, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2f, 0x67, 0x6f,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x74, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_catscope_proto_rawDescOnce sync.Once
	file_catscope_proto_rawDescData = file_catscope_proto_rawDesc
)

func file_catscope_proto_rawDescGZIP() []byte {
	file_catscope_proto_rawDescOnce.Do(func() {
		file_catscope_proto_rawDescData = protoimpl.X.CompressGZIP(file_catscope_proto_rawDescData)
	})
	return file_catscope_proto_rawDescData
}

var file_catscope_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_catscope_proto_goTypes = []interface{}{
	(*Empty)(nil),                // 0: catscopestate.Empty
	(*GetRequest)(nil),           // 1: catscopestate.GetRequest
	(*GetResponse)(nil),          // 2: catscopestate.GetResponse
	(*AccountId)(nil),            // 3: catscopestate.AccountId
	(*Account)(nil),              // 4: catscopestate.Account
	(*SubscriptionRequest)(nil),  // 5: catscopestate.SubscriptionRequest
	(*ChainUpdate)(nil),          // 6: catscopestate.ChainUpdate
	(*Slot)(nil),                 // 7: catscopestate.Slot
	(*Edge)(nil),                 // 8: catscopestate.Edge
	(*SubscriptionResponse)(nil), // 9: catscopestate.SubscriptionResponse
	(*RentRequest)(nil),          // 10: catscopestate.RentRequest
	(*RentResponse)(nil),         // 11: catscopestate.RentResponse
}
var file_catscope_proto_depIdxs = []int32{
	3,  // 0: catscopestate.GetRequest.list_id:type_name -> catscopestate.AccountId
	4,  // 1: catscopestate.GetResponse.list_account:type_name -> catscopestate.Account
	8,  // 2: catscopestate.Account.list_edge_add:type_name -> catscopestate.Edge
	8,  // 3: catscopestate.Account.list_edge_delete:type_name -> catscopestate.Edge
	8,  // 4: catscopestate.Account.list_edge_keep:type_name -> catscopestate.Edge
	3,  // 5: catscopestate.SubscriptionRequest.root:type_name -> catscopestate.AccountId
	7,  // 6: catscopestate.ChainUpdate.slot:type_name -> catscopestate.Slot
	4,  // 7: catscopestate.SubscriptionResponse.list_account:type_name -> catscopestate.Account
	1,  // 8: catscopestate.Graph.Get:input_type -> catscopestate.GetRequest
	5,  // 9: catscopestate.Graph.Subscribe:input_type -> catscopestate.SubscriptionRequest
	0,  // 10: catscopestate.Graph.Chain:input_type -> catscopestate.Empty
	10, // 11: catscopestate.Graph.RentExemption:input_type -> catscopestate.RentRequest
	2,  // 12: catscopestate.Graph.Get:output_type -> catscopestate.GetResponse
	9,  // 13: catscopestate.Graph.Subscribe:output_type -> catscopestate.SubscriptionResponse
	6,  // 14: catscopestate.Graph.Chain:output_type -> catscopestate.ChainUpdate
	11, // 15: catscopestate.Graph.RentExemption:output_type -> catscopestate.RentResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_catscope_proto_init() }
func file_catscope_proto_init() {
	if File_catscope_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_catscope_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catscope_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catscope_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catscope_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catscope_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Account); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catscope_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscriptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catscope_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChainUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catscope_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Slot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catscope_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Edge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catscope_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscriptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catscope_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catscope_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_catscope_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*AccountId_NodeId)(nil),
		(*AccountId_Pubkey)(nil),
	}
	file_catscope_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*ChainUpdate_Slot)(nil),
		(*ChainUpdate_Blockhash)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_catscope_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catscope_proto_goTypes,
		DependencyIndexes: file_catscope_proto_depIdxs,
		MessageInfos:      file_catscope_proto_msgTypes,
	}.Build()
	File_catscope_proto = out.File
	file_catscope_proto_rawDesc = nil
	file_catscope_proto_goTypes = nil
	file_catscope_proto_depIdxs = nil
}
