// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: bot.proto

package bot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_Compiling Status = 0
	Status_Frozen    Status = 1
	Status_Running   Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Compiling",
		1: "Frozen",
		2: "Running",
	}
	Status_value = map[string]int32{
		"Compiling": 0,
		"Frozen":    1,
		"Running":   2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_bot_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_bot_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_bot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{0}
}

type BotUploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*BotUploadRequest_Header
	//	*BotUploadRequest_Body
	Payload       isBotUploadRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotUploadRequest) Reset() {
	*x = BotUploadRequest{}
	mi := &file_bot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotUploadRequest) ProtoMessage() {}

func (x *BotUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotUploadRequest.ProtoReflect.Descriptor instead.
func (*BotUploadRequest) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{1}
}

func (x *BotUploadRequest) GetPayload() isBotUploadRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BotUploadRequest) GetHeader() *BotHeader {
	if x != nil {
		if x, ok := x.Payload.(*BotUploadRequest_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *BotUploadRequest) GetBody() *BotBody {
	if x != nil {
		if x, ok := x.Payload.(*BotUploadRequest_Body); ok {
			return x.Body
		}
	}
	return nil
}

type isBotUploadRequest_Payload interface {
	isBotUploadRequest_Payload()
}

type BotUploadRequest_Header struct {
	Header *BotHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type BotUploadRequest_Body struct {
	Body *BotBody `protobuf:"bytes,2,opt,name=body,proto3,oneof"`
}

func (*BotUploadRequest_Header) isBotUploadRequest_Payload() {}

func (*BotUploadRequest_Body) isBotUploadRequest_Payload() {}

type BotUploadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*BotUploadResponse_Out
	//	*BotUploadResponse_Result
	Response      isBotUploadResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotUploadResponse) Reset() {
	*x = BotUploadResponse{}
	mi := &file_bot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotUploadResponse) ProtoMessage() {}

func (x *BotUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotUploadResponse.ProtoReflect.Descriptor instead.
func (*BotUploadResponse) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{2}
}

func (x *BotUploadResponse) GetResponse() isBotUploadResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *BotUploadResponse) GetOut() *BotOut {
	if x != nil {
		if x, ok := x.Response.(*BotUploadResponse_Out); ok {
			return x.Out
		}
	}
	return nil
}

func (x *BotUploadResponse) GetResult() *BotStatus {
	if x != nil {
		if x, ok := x.Response.(*BotUploadResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isBotUploadResponse_Response interface {
	isBotUploadResponse_Response()
}

type BotUploadResponse_Out struct {
	Out *BotOut `protobuf:"bytes,1,opt,name=out,proto3,oneof"`
}

type BotUploadResponse_Result struct {
	Result *BotStatus `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

func (*BotUploadResponse_Out) isBotUploadResponse_Response() {}

func (*BotUploadResponse_Result) isBotUploadResponse_Response() {}

type BotHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// this is a sha256 sum of the wasm body.
	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// make the size as 0 when there is no bot being stored in the validator.
	Size          uint32            `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Env           map[string]string `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Args          []string          `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotHeader) Reset() {
	*x = BotHeader{}
	mi := &file_bot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotHeader) ProtoMessage() {}

func (x *BotHeader) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotHeader.ProtoReflect.Descriptor instead.
func (*BotHeader) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{3}
}

func (x *BotHeader) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *BotHeader) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BotHeader) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *BotHeader) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type BotBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotBody) Reset() {
	*x = BotBody{}
	mi := &file_bot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotBody) ProtoMessage() {}

func (x *BotBody) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotBody.ProtoReflect.Descriptor instead.
func (*BotBody) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{4}
}

func (x *BotBody) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*BotStatus           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_bot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetList() []*BotStatus {
	if x != nil {
		return x.List
	}
	return nil
}

type BotStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *BotHeader             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Status        *StatusTime            `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotStatus) Reset() {
	*x = BotStatus{}
	mi := &file_bot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotStatus) ProtoMessage() {}

func (x *BotStatus) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotStatus.ProtoReflect.Descriptor instead.
func (*BotStatus) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{6}
}

func (x *BotStatus) GetHeader() *BotHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *BotStatus) GetStatus() *StatusTime {
	if x != nil {
		return x.Status
	}
	return nil
}

type BotIn struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to In:
	//
	//	*BotIn_Hash
	//	*BotIn_Stdin
	In            isBotIn_In `protobuf_oneof:"in"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotIn) Reset() {
	*x = BotIn{}
	mi := &file_bot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotIn) ProtoMessage() {}

func (x *BotIn) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotIn.ProtoReflect.Descriptor instead.
func (*BotIn) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{7}
}

func (x *BotIn) GetIn() isBotIn_In {
	if x != nil {
		return x.In
	}
	return nil
}

func (x *BotIn) GetHash() []byte {
	if x != nil {
		if x, ok := x.In.(*BotIn_Hash); ok {
			return x.Hash
		}
	}
	return nil
}

func (x *BotIn) GetStdin() []byte {
	if x != nil {
		if x, ok := x.In.(*BotIn_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

type isBotIn_In interface {
	isBotIn_In()
}

type BotIn_Hash struct {
	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3,oneof"`
}

type BotIn_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

func (*BotIn_Hash) isBotIn_In() {}

func (*BotIn_Stdin) isBotIn_In() {}

type BotOut struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Out:
	//
	//	*BotOut_Stdout
	//	*BotOut_Stderr
	//	*BotOut_KeypairPubkey
	//	*BotOut_Exit
	//	*BotOut_Status
	//	*BotOut_KeepAlive
	Out           isBotOut_Out `protobuf_oneof:"out"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotOut) Reset() {
	*x = BotOut{}
	mi := &file_bot_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotOut) ProtoMessage() {}

func (x *BotOut) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotOut.ProtoReflect.Descriptor instead.
func (*BotOut) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{8}
}

func (x *BotOut) GetOut() isBotOut_Out {
	if x != nil {
		return x.Out
	}
	return nil
}

func (x *BotOut) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Out.(*BotOut_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *BotOut) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Out.(*BotOut_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *BotOut) GetKeypairPubkey() []byte {
	if x != nil {
		if x, ok := x.Out.(*BotOut_KeypairPubkey); ok {
			return x.KeypairPubkey
		}
	}
	return nil
}

func (x *BotOut) GetExit() string {
	if x != nil {
		if x, ok := x.Out.(*BotOut_Exit); ok {
			return x.Exit
		}
	}
	return ""
}

func (x *BotOut) GetStatus() *StatusTime {
	if x != nil {
		if x, ok := x.Out.(*BotOut_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *BotOut) GetKeepAlive() *BotOut {
	if x != nil {
		if x, ok := x.Out.(*BotOut_KeepAlive); ok {
			return x.KeepAlive
		}
	}
	return nil
}

type isBotOut_Out interface {
	isBotOut_Out()
}

type BotOut_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type BotOut_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type BotOut_KeypairPubkey struct {
	// a private key with this public key has been generated by the wasm bot
	KeypairPubkey []byte `protobuf:"bytes,3,opt,name=keypair_pubkey,json=keypairPubkey,proto3,oneof"`
}

type BotOut_Exit struct {
	Exit string `protobuf:"bytes,4,opt,name=exit,proto3,oneof"`
}

type BotOut_Status struct {
	Status *StatusTime `protobuf:"bytes,5,opt,name=status,proto3,oneof"`
}

type BotOut_KeepAlive struct {
	KeepAlive *BotOut `protobuf:"bytes,6,opt,name=keep_alive,json=keepAlive,proto3,oneof"`
}

func (*BotOut_Stdout) isBotOut_Out() {}

func (*BotOut_Stderr) isBotOut_Out() {}

func (*BotOut_KeypairPubkey) isBotOut_Out() {}

func (*BotOut_Exit) isBotOut_Out() {}

func (*BotOut_Status) isBotOut_Out() {}

func (*BotOut_KeepAlive) isBotOut_Out() {}

type StatusTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=bot.Status" json:"status,omitempty"`
	Time          int64                  `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusTime) Reset() {
	*x = StatusTime{}
	mi := &file_bot_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusTime) ProtoMessage() {}

func (x *StatusTime) ProtoReflect() protoreflect.Message {
	mi := &file_bot_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusTime.ProtoReflect.Descriptor instead.
func (*StatusTime) Descriptor() ([]byte, []int) {
	return file_bot_proto_rawDescGZIP(), []int{9}
}

func (x *StatusTime) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Compiling
}

func (x *StatusTime) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

var File_bot_proto protoreflect.FileDescriptor

var file_bot_proto_rawDesc = string([]byte{
	0x0a, 0x09, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x62, 0x6f, 0x74,
	0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x6b, 0x0a, 0x10, 0x42, 0x6f, 0x74,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x62, 0x6f, 0x74, 0x2e, 0x42, 0x6f, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x48, 0x00, 0x52,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x62, 0x6f, 0x74, 0x2e, 0x42, 0x6f, 0x74, 0x42,
	0x6f, 0x64, 0x79, 0x48, 0x00, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x42, 0x09, 0x0a, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x6a, 0x0a, 0x11, 0x42, 0x6f, 0x74, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x03, 0x6f,
	0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x62, 0x6f, 0x74, 0x2e, 0x42,
	0x6f, 0x74, 0x4f, 0x75, 0x74, 0x48, 0x00, 0x52, 0x03, 0x6f, 0x75, 0x74, 0x12, 0x28, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62,
	0x6f, 0x74, 0x2e, 0x42, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0xaa, 0x01, 0x0a, 0x09, 0x42, 0x6f, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x68, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x29, 0x0a, 0x03, 0x65, 0x6e, 0x76, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x62, 0x6f, 0x74, 0x2e, 0x42, 0x6f, 0x74, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x45, 0x6e, 0x76, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x03,
	0x65, 0x6e, 0x76, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x1a, 0x36, 0x0a, 0x08, 0x45, 0x6e, 0x76, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0x1d, 0x0a, 0x07, 0x42, 0x6f, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x34,
	0x0a, 0x0e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x22, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x62, 0x6f, 0x74, 0x2e, 0x42, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x22, 0x5c, 0x0a, 0x09, 0x42, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x26, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x6f, 0x74, 0x2e, 0x42, 0x6f, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x6f, 0x74, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x3b, 0x0a, 0x05, 0x42, 0x6f, 0x74, 0x49, 0x6e, 0x12, 0x14, 0x0a, 0x04, 0x68,
	0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x12, 0x16, 0x0a, 0x05, 0x73, 0x74, 0x64, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x64, 0x69, 0x6e, 0x42, 0x04, 0x0a, 0x02, 0x69, 0x6e, 0x22,
	0xdb, 0x01, 0x0a, 0x06, 0x42, 0x6f, 0x74, 0x4f, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x74,
	0x64, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74,
	0x64, 0x6f, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72, 0x12, 0x27,
	0x0a, 0x0e, 0x6b, 0x65, 0x79, 0x70, 0x61, 0x69, 0x72, 0x5f, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0d, 0x6b, 0x65, 0x79, 0x70, 0x61, 0x69,
	0x72, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x04, 0x65, 0x78, 0x69, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x65, 0x78, 0x69, 0x74, 0x12, 0x29, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x62, 0x6f, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x48, 0x00,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2c, 0x0a, 0x0a, 0x6b, 0x65, 0x65, 0x70,
	0x5f, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x62,
	0x6f, 0x74, 0x2e, 0x42, 0x6f, 0x74, 0x4f, 0x75, 0x74, 0x48, 0x00, 0x52, 0x09, 0x6b, 0x65, 0x65,
	0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x42, 0x05, 0x0a, 0x03, 0x6f, 0x75, 0x74, 0x22, 0x45, 0x0a,
	0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x62, 0x6f,
	0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x74, 0x69, 0x6d, 0x65, 0x2a, 0x30, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0d,
	0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x0a, 0x0a,
	0x06, 0x46, 0x72, 0x6f, 0x7a, 0x65, 0x6e, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x75, 0x6e,
	0x6e, 0x69, 0x6e, 0x67, 0x10, 0x02, 0x32, 0x9a, 0x01, 0x0a, 0x03, 0x42, 0x6f, 0x74, 0x12, 0x3d,
	0x0a, 0x06, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x15, 0x2e, 0x62, 0x6f, 0x74, 0x2e, 0x42,
	0x6f, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x62, 0x6f, 0x74, 0x2e, 0x42, 0x6f, 0x74, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x2e, 0x0a,
	0x09, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0a, 0x2e, 0x62, 0x6f, 0x74,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x13, 0x2e, 0x62, 0x6f, 0x74, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x24, 0x0a,
	0x03, 0x52, 0x75, 0x6e, 0x12, 0x0a, 0x2e, 0x62, 0x6f, 0x74, 0x2e, 0x42, 0x6f, 0x74, 0x49, 0x6e,
	0x1a, 0x0b, 0x2e, 0x62, 0x6f, 0x74, 0x2e, 0x42, 0x6f, 0x74, 0x4f, 0x75, 0x74, 0x22, 0x00, 0x28,
	0x01, 0x30, 0x01, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x61, 0x64, 0x2f, 0x73, 0x6f, 0x6c, 0x70, 0x69,
	0x70, 0x65, 0x2d, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x62, 0x6f, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_bot_proto_rawDescOnce sync.Once
	file_bot_proto_rawDescData []byte
)

func file_bot_proto_rawDescGZIP() []byte {
	file_bot_proto_rawDescOnce.Do(func() {
		file_bot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bot_proto_rawDesc), len(file_bot_proto_rawDesc)))
	})
	return file_bot_proto_rawDescData
}

var file_bot_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bot_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_bot_proto_goTypes = []any{
	(Status)(0),               // 0: bot.Status
	(*Empty)(nil),             // 1: bot.Empty
	(*BotUploadRequest)(nil),  // 2: bot.BotUploadRequest
	(*BotUploadResponse)(nil), // 3: bot.BotUploadResponse
	(*BotHeader)(nil),         // 4: bot.BotHeader
	(*BotBody)(nil),           // 5: bot.BotBody
	(*StatusResponse)(nil),    // 6: bot.StatusResponse
	(*BotStatus)(nil),         // 7: bot.BotStatus
	(*BotIn)(nil),             // 8: bot.BotIn
	(*BotOut)(nil),            // 9: bot.BotOut
	(*StatusTime)(nil),        // 10: bot.StatusTime
	nil,                       // 11: bot.BotHeader.EnvEntry
}
var file_bot_proto_depIdxs = []int32{
	4,  // 0: bot.BotUploadRequest.header:type_name -> bot.BotHeader
	5,  // 1: bot.BotUploadRequest.body:type_name -> bot.BotBody
	9,  // 2: bot.BotUploadResponse.out:type_name -> bot.BotOut
	7,  // 3: bot.BotUploadResponse.result:type_name -> bot.BotStatus
	11, // 4: bot.BotHeader.env:type_name -> bot.BotHeader.EnvEntry
	7,  // 5: bot.StatusResponse.list:type_name -> bot.BotStatus
	4,  // 6: bot.BotStatus.header:type_name -> bot.BotHeader
	10, // 7: bot.BotStatus.status:type_name -> bot.StatusTime
	10, // 8: bot.BotOut.status:type_name -> bot.StatusTime
	9,  // 9: bot.BotOut.keep_alive:type_name -> bot.BotOut
	0,  // 10: bot.StatusTime.status:type_name -> bot.Status
	2,  // 11: bot.Bot.Upload:input_type -> bot.BotUploadRequest
	1,  // 12: bot.Bot.GetStatus:input_type -> bot.Empty
	8,  // 13: bot.Bot.Run:input_type -> bot.BotIn
	3,  // 14: bot.Bot.Upload:output_type -> bot.BotUploadResponse
	6,  // 15: bot.Bot.GetStatus:output_type -> bot.StatusResponse
	9,  // 16: bot.Bot.Run:output_type -> bot.BotOut
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_bot_proto_init() }
func file_bot_proto_init() {
	if File_bot_proto != nil {
		return
	}
	file_bot_proto_msgTypes[1].OneofWrappers = []any{
		(*BotUploadRequest_Header)(nil),
		(*BotUploadRequest_Body)(nil),
	}
	file_bot_proto_msgTypes[2].OneofWrappers = []any{
		(*BotUploadResponse_Out)(nil),
		(*BotUploadResponse_Result)(nil),
	}
	file_bot_proto_msgTypes[7].OneofWrappers = []any{
		(*BotIn_Hash)(nil),
		(*BotIn_Stdin)(nil),
	}
	file_bot_proto_msgTypes[8].OneofWrappers = []any{
		(*BotOut_Stdout)(nil),
		(*BotOut_Stderr)(nil),
		(*BotOut_KeypairPubkey)(nil),
		(*BotOut_Exit)(nil),
		(*BotOut_Status)(nil),
		(*BotOut_KeepAlive)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bot_proto_rawDesc), len(file_bot_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bot_proto_goTypes,
		DependencyIndexes: file_bot_proto_depIdxs,
		EnumInfos:         file_bot_proto_enumTypes,
		MessageInfos:      file_bot_proto_msgTypes,
	}.Build()
	File_bot_proto = out.File
	file_bot_proto_goTypes = nil
	file_bot_proto_depIdxs = nil
}
