// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: solpipe.proto

package solpipe

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Tree_Get_FullMethodName             = "/solpipestate.Tree/Get"
	Tree_GetTreeByPubkey_FullMethodName = "/solpipestate.Tree/GetTreeByPubkey"
	Tree_Stream_FullMethodName          = "/solpipestate.Tree/Stream"
	Tree_OnSol_FullMethodName           = "/solpipestate.Tree/OnSol"
	Tree_OnToken_FullMethodName         = "/solpipestate.Tree/OnToken"
	Tree_OnSlot_FullMethodName          = "/solpipestate.Tree/OnSlot"
)

// TreeClient is the client API for Tree service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TreeClient interface {
	// just get a single request
	Get(ctx context.Context, in *SingleRequest, opts ...grpc.CallOption) (*Notification, error)
	// receive requested notifications and chain state updates
	GetTreeByPubkey(ctx context.Context, in *TreeRequest, opts ...grpc.CallOption) (*TreeResponse, error)
	Stream(ctx context.Context, opts ...grpc.CallOption) (Tree_StreamClient, error)
	OnSol(ctx context.Context, in *SolRequest, opts ...grpc.CallOption) (Tree_OnSolClient, error)
	OnToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (Tree_OnTokenClient, error)
	OnSlot(ctx context.Context, in *SlotRequest, opts ...grpc.CallOption) (Tree_OnSlotClient, error)
}

type treeClient struct {
	cc grpc.ClientConnInterface
}

func NewTreeClient(cc grpc.ClientConnInterface) TreeClient {
	return &treeClient{cc}
}

func (c *treeClient) Get(ctx context.Context, in *SingleRequest, opts ...grpc.CallOption) (*Notification, error) {
	out := new(Notification)
	err := c.cc.Invoke(ctx, Tree_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeClient) GetTreeByPubkey(ctx context.Context, in *TreeRequest, opts ...grpc.CallOption) (*TreeResponse, error) {
	out := new(TreeResponse)
	err := c.cc.Invoke(ctx, Tree_GetTreeByPubkey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeClient) Stream(ctx context.Context, opts ...grpc.CallOption) (Tree_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Tree_ServiceDesc.Streams[0], Tree_Stream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &treeStreamClient{stream}
	return x, nil
}

type Tree_StreamClient interface {
	Send(*StreamRequest) error
	Recv() (*StreamResponse, error)
	grpc.ClientStream
}

type treeStreamClient struct {
	grpc.ClientStream
}

func (x *treeStreamClient) Send(m *StreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *treeStreamClient) Recv() (*StreamResponse, error) {
	m := new(StreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *treeClient) OnSol(ctx context.Context, in *SolRequest, opts ...grpc.CallOption) (Tree_OnSolClient, error) {
	stream, err := c.cc.NewStream(ctx, &Tree_ServiceDesc.Streams[1], Tree_OnSol_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &treeOnSolClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Tree_OnSolClient interface {
	Recv() (*SolResponse, error)
	grpc.ClientStream
}

type treeOnSolClient struct {
	grpc.ClientStream
}

func (x *treeOnSolClient) Recv() (*SolResponse, error) {
	m := new(SolResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *treeClient) OnToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (Tree_OnTokenClient, error) {
	stream, err := c.cc.NewStream(ctx, &Tree_ServiceDesc.Streams[2], Tree_OnToken_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &treeOnTokenClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Tree_OnTokenClient interface {
	Recv() (*TokenResponse, error)
	grpc.ClientStream
}

type treeOnTokenClient struct {
	grpc.ClientStream
}

func (x *treeOnTokenClient) Recv() (*TokenResponse, error) {
	m := new(TokenResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *treeClient) OnSlot(ctx context.Context, in *SlotRequest, opts ...grpc.CallOption) (Tree_OnSlotClient, error) {
	stream, err := c.cc.NewStream(ctx, &Tree_ServiceDesc.Streams[3], Tree_OnSlot_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &treeOnSlotClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Tree_OnSlotClient interface {
	Recv() (*SlotResponse, error)
	grpc.ClientStream
}

type treeOnSlotClient struct {
	grpc.ClientStream
}

func (x *treeOnSlotClient) Recv() (*SlotResponse, error) {
	m := new(SlotResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TreeServer is the server API for Tree service.
// All implementations must embed UnimplementedTreeServer
// for forward compatibility
type TreeServer interface {
	// just get a single request
	Get(context.Context, *SingleRequest) (*Notification, error)
	// receive requested notifications and chain state updates
	GetTreeByPubkey(context.Context, *TreeRequest) (*TreeResponse, error)
	Stream(Tree_StreamServer) error
	OnSol(*SolRequest, Tree_OnSolServer) error
	OnToken(*TokenRequest, Tree_OnTokenServer) error
	OnSlot(*SlotRequest, Tree_OnSlotServer) error
	mustEmbedUnimplementedTreeServer()
}

// UnimplementedTreeServer must be embedded to have forward compatible implementations.
type UnimplementedTreeServer struct {
}

func (UnimplementedTreeServer) Get(context.Context, *SingleRequest) (*Notification, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedTreeServer) GetTreeByPubkey(context.Context, *TreeRequest) (*TreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTreeByPubkey not implemented")
}
func (UnimplementedTreeServer) Stream(Tree_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedTreeServer) OnSol(*SolRequest, Tree_OnSolServer) error {
	return status.Errorf(codes.Unimplemented, "method OnSol not implemented")
}
func (UnimplementedTreeServer) OnToken(*TokenRequest, Tree_OnTokenServer) error {
	return status.Errorf(codes.Unimplemented, "method OnToken not implemented")
}
func (UnimplementedTreeServer) OnSlot(*SlotRequest, Tree_OnSlotServer) error {
	return status.Errorf(codes.Unimplemented, "method OnSlot not implemented")
}
func (UnimplementedTreeServer) mustEmbedUnimplementedTreeServer() {}

// UnsafeTreeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TreeServer will
// result in compilation errors.
type UnsafeTreeServer interface {
	mustEmbedUnimplementedTreeServer()
}

func RegisterTreeServer(s grpc.ServiceRegistrar, srv TreeServer) {
	s.RegisterService(&Tree_ServiceDesc, srv)
}

func _Tree_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SingleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tree_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServer).Get(ctx, req.(*SingleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tree_GetTreeByPubkey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServer).GetTreeByPubkey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tree_GetTreeByPubkey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServer).GetTreeByPubkey(ctx, req.(*TreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tree_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TreeServer).Stream(&treeStreamServer{stream})
}

type Tree_StreamServer interface {
	Send(*StreamResponse) error
	Recv() (*StreamRequest, error)
	grpc.ServerStream
}

type treeStreamServer struct {
	grpc.ServerStream
}

func (x *treeStreamServer) Send(m *StreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *treeStreamServer) Recv() (*StreamRequest, error) {
	m := new(StreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Tree_OnSol_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SolRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TreeServer).OnSol(m, &treeOnSolServer{stream})
}

type Tree_OnSolServer interface {
	Send(*SolResponse) error
	grpc.ServerStream
}

type treeOnSolServer struct {
	grpc.ServerStream
}

func (x *treeOnSolServer) Send(m *SolResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Tree_OnToken_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TokenRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TreeServer).OnToken(m, &treeOnTokenServer{stream})
}

type Tree_OnTokenServer interface {
	Send(*TokenResponse) error
	grpc.ServerStream
}

type treeOnTokenServer struct {
	grpc.ServerStream
}

func (x *treeOnTokenServer) Send(m *TokenResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Tree_OnSlot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SlotRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TreeServer).OnSlot(m, &treeOnSlotServer{stream})
}

type Tree_OnSlotServer interface {
	Send(*SlotResponse) error
	grpc.ServerStream
}

type treeOnSlotServer struct {
	grpc.ServerStream
}

func (x *treeOnSlotServer) Send(m *SlotResponse) error {
	return x.ServerStream.SendMsg(m)
}

// Tree_ServiceDesc is the grpc.ServiceDesc for Tree service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tree_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "solpipestate.Tree",
	HandlerType: (*TreeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Tree_Get_Handler,
		},
		{
			MethodName: "GetTreeByPubkey",
			Handler:    _Tree_GetTreeByPubkey_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Tree_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "OnSol",
			Handler:       _Tree_OnSol_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "OnToken",
			Handler:       _Tree_OnToken_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "OnSlot",
			Handler:       _Tree_OnSlot_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "solpipe.proto",
}
